[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.poetry]
name = "express-relay-utils"
version = 0.0.1
dependencies = [
    "web3",
    "eth_abi",
    "eth_account",
    "httpx",
    "websockets",
    "asyncio",
    "argparse"
]
description = "Utilities for searchers and protocols to interact with the express relay protocol."
license = "Proprietary"
readme = "README.md"
